name: first workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout code

      - name: install dependencies
        run: npm install
        shell: bash

      - name: run build
        run: npm run build
        shell: bash


  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout code

      - name: install dependencies
        run: npm install
        shell: bash

      - name: run tests
        run: npm run test
        shell: bash

  lint:
    name: 'Run linter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout code

      - name: install dependencies
        run: npm install
        shell: bash
      
      - name: 'Run linter'
        run: npx eslint